const group0002 = /* GraphQL */ `
  {
    items {
      name
      about
      aura
      category {
        createdAt
        icon
        id
        name
        updatedAt
      }
      category_id
      cover {
        bucket
        createdAt
        ext
        external_url
        id
        isExternal
        key
        level
        name
        owner
        provided_item
        provider
        region
        type
        updatedAt
      }
      createdAt
      featured
      followed
      founder {
        about
        age
        aura
        birthdate
        cover_pic_id
        createdAt
        employed
        firstname
        followed
        gender
        id
        is_public
        lastname
        meta
        nickname
        pic {
          bucket
          createdAt
          ext
          external_url
          id
          isExternal
          key
          level
          name
          owner
          provided_item
          provider
          region
          type
          updatedAt
        }
        pic_id
        status
        updatedAt
        verified
      }
      founder_id
      g_attentions
      g_rules
      id
      rating
      role_on_group
      totals {
        admin
        confirmed
        createdAt
        group_id
        member
        moderator
        pending
        search_id
        unseen
        updatedAt
      }
      updatedAt
      profile {
        bucket
        createdAt
        ext
        external_url
        id
        isExternal
        key
        level
        name
        owner
        provided_item
        provider
        region
        type
        updatedAt
      }
    }
    nextToken
  }
`;

export default group0002;
